"""add total_seasons and total_episodes to movie

Revision ID: 1b682bbd61af
Revises: 581edf8006d4
Create Date: 2026-07-16 21:56:48.526917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b682bbd61af'
down_revision: Union[str, Sequence[str], None] = '581edf8006d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('total_seasons', sa.Integer(), nullable=True))
    op.add_column('movie', sa.Column('total_episodes', sa.Integer(), nullable=True))
    op.add_column('movie', sa.Column('last_checked_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'last_checked_at')
    op.drop_column('movie', 'total_episodes')
    op.drop_column('movie', 'total_seasons')
    # ### end Alembic commands ###
