"""update movie

Revision ID: 959c516923e2
Revises: 
Create Date: 2026-06-18 22:11:31.712313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '959c516923e2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_kino', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('alternative_name', sa.String(), nullable=True),
    sa.Column('movie_type', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('short_description', sa.String(), nullable=True),
    sa.Column('is_series', sa.Boolean(), nullable=False),
    sa.Column('rating_kp', sa.Float(), nullable=True),
    sa.Column('rating_imdb', sa.Float(), nullable=True),
    sa.Column('genres', sa.JSON(), nullable=True),
    sa.Column('countries', sa.JSON(), nullable=True),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('poster', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_id_kino'), 'movie', ['id_kino'], unique=True)
    op.create_index(op.f('ix_movie_name'), 'movie', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movie_name'), table_name='movie')
    op.drop_index(op.f('ix_movie_id_kino'), table_name='movie')
    op.drop_table('movie')
    # ### end Alembic commands ###
