"""add is_tracking to user_movie

Revision ID: bf83c98306ff
Revises: 1b682bbd61af
Create Date: 2026-07-29 18:57:08.182020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf83c98306ff'
down_revision: Union[str, Sequence[str], None] = '1b682bbd61af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_movie', sa.Column('is_tracking', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_movie', 'is_tracking')
    # ### end Alembic commands ###
